### ISSUE TITLE
Implement features for Ui

### ISSUE THREAD

**Issue by yuhongtay** [AY1920S1-CS2103-T16-4/main#60]
- [x] Hide wishlist/reminder
- [x] Set font (#128, #129)
- [x] Set Dark/Light theme
- [x] Allow user to see budgets/wish/reminders in main panel through various list commands

**Comment by jessicax941** [comment]
- [ ] change look of entrycard
- [ ] make light theme
- [ ] add panel for wishlist
- [ ] add panel for budget
- [ ] add panel for reminder
